-- Defensive migration for CI lane: guarantees cart tables exist before Hibernate validate.

CREATE TABLE IF NOT EXISTS carts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.table_constraints
        WHERE constraint_name = 'fk_cart_items_cart'
          AND table_name = 'cart_items'
    ) THEN
        ALTER TABLE cart_items
            ADD CONSTRAINT fk_cart_items_cart
            FOREIGN KEY (cart_id) REFERENCES carts (id);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.table_constraints
        WHERE constraint_name = 'fk_cart_items_product'
          AND table_name = 'cart_items'
    ) THEN
        ALTER TABLE cart_items
            ADD CONSTRAINT fk_cart_items_product
            FOREIGN KEY (product_id) REFERENCES products (id);
    END IF;
END $$;
